defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres


development:
  database: ror-test
  password: testtest
  <<: *defaults

test: &TEST
  database: ror-test
  password: testtest
  <<: *defaults

production:
  database: ror-test
  password: testtest
  <<: *defaults




